.PHONY: clean

clean:
	rm -f *~ *.out out
	cp template/a.cpp a.cpp
	cp template/a.cpp b.cpp
	cp template/a.cpp c.cpp
	cp template/a.cpp d.cpp
	cp template/in.txt in1.txt
	cp template/in.txt in2.txt
	cp template/in.txt in3.txt
